services:
  hope:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "${configPath}:/app/config/"
  bdd:
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    volumes:
      - "${bddPath}:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: "superSecuredPassword"
